#!/usr/bin/node

let ask = require('readline-sync')

let name
let age 

// console.log("typeof(name)", typeof(name)) // Undefined, the interpreter cannot know the type to attribute.
// console.log("typeof(age)",  typeof(age))  // Same here

name = process.argv[2] 
age  = parseInt(process.argv[3])

// console.log("typeof \"",name,"\"",typeof(name)) Undefined if argc < 2, a string if argc >= 2
// console.log("typeof \"",age,"\"",typeof(age))   Undefined if argc < 3 or invalid number, otherwise it will be a number

if (process.argv[2] == null && process.argv[3] == null)
{
	name = ask.question("Digite seu nome: ")
	age  = parseInt(ask.question("Digite sua idade: "))
	if (isNaN(age))
	{
		console.log("Número inválido fornecido como idade.")
		process.exit(1)
	}
}

if (isNaN(age) && process.argv[3] !== null) 
{
	console.log("Uso:", process.argv[1], "[nome] [idade]")
	console.log("Onde nome é uma string e idade é um número válido.")
	process.exit(1)
}

console.log(`Olá ${name}, você têm ${age} anos.`)

