#!/usr/bin/node

let a = 10
let b = 25

console.log("O valor de a é", a)
console.log("O valor de b é", b)

let c = a // Receives 10
a = b     // Receives 25
b = c     // Receives 10


console.log(`O novo valor de a é ${a}`)
console.log(`O novo valor de b é ${b}`)

